displayName=Flinch
author=Tommy Turnip
description=Play an emote or dodge animation on yourself when you take a 0, take damage, get poisoned or die
tags=animation,emote,dodge,hitsplat,cosmetic,flinch
version=1.0.0
plugins=com.tommyknight.flinch.FlinchPlugin
build=standard
